In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
# Task 1 

# Q1(a) Generate Array A with 100 random integers


np.random.seed(42)  

A = np.random.randint(1, 101, 100)

print("Q1(a) Array A (first 10 values):")
print(A[:10])


print("Minimum:", np.min(A))
print("Maximum:", np.max(A))
print("Median:", np.median(A))
print("Mean:", np.mean(A))
print("Standard Deviation:", np.std(A))

print("\n---\n")

# Q1(b) Generate Array B using np.arange()


B = np.arange(1, 101)

print("Q1(b) Array B (first 10 values):")
print(B[:10])

print("\n---\n")

# Q1(c) Implement np.zeros() and np.ones()


zeros_array = np.zeros(5)
ones_array = np.ones(5)

print("Q1(c)")
print("Zeros array:", zeros_array)
print("Ones array:", ones_array)

print("Shape of zeros array:", zeros_array.shape)
print("Data type of zeros array:", zeros_array.dtype)

print("\n---\n")




Q1(a) Array A (first 10 values):
[52 93 15 72 61 21 83 87 75 75]
Minimum: 2
Maximum: 100
Median: 54.0
Mean: 51.54
Standard Deviation: 29.278463074417004

---

Q1(b) Array B (first 10 values):
[ 1  2  3  4  5  6  7  8  9 10]

---

Q1(c)
Zeros array: [0. 0. 0. 0. 0.]
Ones array: [1. 1. 1. 1. 1.]
Shape of zeros array: (5,)
Data type of zeros array: float64

---

Q1(d) np.linspace():
[ 0.   2.5  5.   7.5 10. ]
Difference from np.arange():
np.arange() uses a step size, while np.linspace() creates a fixed number of equally spaced values.

---



In [18]:
# Q1(d) Implement np.linspace()


lin = np.linspace(0, 10, 5)

print("Q1(d) np.linspace():")
print(lin)

print("Difference from np.arange():")
print("np.arange() uses a step size, while np.linspace() creates a fixed number of equally spaced values.")

print("\n---\n")


Q1(d) np.linspace():
[ 0.   2.5  5.   7.5 10. ]
Difference from np.arange():
np.arange() uses a step size, while np.linspace() creates a fixed number of equally spaced values.

---



In [19]:
# Q1(e) Create one 2D and one 3D array


arr2d = np.arange(1, 13).reshape(3, 4)

print("Q1(e) 2D Array:")
print(arr2d)

print("Shape:", arr2d.shape)
print("ndim:", arr2d.ndim)

# Indexing
print("Element at row 2, column 3:", arr2d[1, 2])

# Rows and columns
print("First row:", arr2d[0])
print("Second column:", arr2d[:, 1])

# Slicing
print("Top-left 2x2 slice:")
print(arr2d[:2, :2])

print("\n---\n")

# 3D Array
arr3d = np.arange(24).reshape(2, 3, 4)

print("3D Array:")
print(arr3d)

print("Shape:", arr3d.shape)
print("ndim:", arr3d.ndim)

# Indexing and slicing
print("Element [1,2,3]:", arr3d[1, 2, 3])

print("First block:")
print(arr3d[0])

print("Slice arr3d[:, :2, :2]:")
print(arr3d[:, :2, :2])

print("\n---\n")

Q1(e) 2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
ndim: 2
Element at row 2, column 3: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Top-left 2x2 slice:
[[1 2]
 [5 6]]

---

3D Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)
ndim: 3
Element [1,2,3]: 23
First block:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Slice arr3d[:, :2, :2]:
[[[ 0  1]
  [ 4  5]]

 [[12 13]
  [16 17]]]

---



In [ ]:

# Q1(f) Reshape and flatten


matrix = A.reshape(10, 10)

print("Q1(f) Reshaped matrix shape:", matrix.shape)

flat = matrix.flatten()

print("Flattened array shape:", flat.shape)
print("First 10 flattened values:", flat[:10])

Q1(f) Reshaped matrix shape: (10, 10)
Flattened array shape: (100,)
First 10 flattened values: [52 93 15 72 61 21 83 87 75 75]


In [21]:

# Task 2 

# Q2(a) Create two matrices


A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\n---\n")

# Q2(b) Matrix addition


print("Addition (A + B):")
print(A + B)

print("\n---\n")


# Q2(c) Element-wise multiplication


print("Element-wise Multiplication (A * B):")
print(A * B)

print("\n---\n")



Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

---

Addition (A + B):
[[ 6  8]
 [10 12]]

---

Element-wise Multiplication (A * B):
[[ 5 12]
 [21 32]]

---



In [24]:
# Q2(d) Matrix multiplication


print("Matrix Multiplication (A @ B):")
print(A @ B)

print("\n---\n")

# Q2(e) Transpose and Determinant


print("Transpose of A:")
print(A.T)

print("\nDeterminant of A:")
print(np.linalg.det(A))

print("\n---\n")




Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]

---

Transpose of A:
[[1 3]
 [2 4]]

Determinant of A:
-2.0000000000000004

---



In [23]:
# Q2(f) Inverse and Verification


inverse_A = np.linalg.inv(A)

print("Inverse of A:")
print(inverse_A)

print("\nVerification A @ A^-1:")
print(A @ inverse_A)

print("\nIs it approximately identity matrix?")
print(np.allclose(A @ inverse_A, np.eye(2)))

print("\n---\n")

# Q2(g) Vectorized NumPy operations (no loops)


vector = np.arange(1, 11)

print("Original vector:", vector)

print("Square of vector:", vector**2)

print("Sine of vector:", np.sin(vector))

print("Vector + 10:", vector + 10)



Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Verification A @ A^-1:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Is it approximately identity matrix?
True

---

Original vector: [ 1  2  3  4  5  6  7  8  9 10]
Square of vector: [  1   4   9  16  25  36  49  64  81 100]
Sine of vector: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
Vector + 10: [11 12 13 14 15 16 17 18 19 20]
